/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Control.ControlNegocio;
import Control.CordinadorPresentacion;
import enumm.estadoAsiento;
import itson.rutappdto.AsientoDTO;
import itson.rutappdto.CamionDTO;
import itson.rutappdto.ViajeDTO;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mmax2
 */
public class ViajesDisponibles extends javax.swing.JFrame {
    
    public List<AsientoDTO> listaAsiento = CreaAsientos();
    
    public List<AsientoDTO> CreaAsientos (){
        List<AsientoDTO> asientos;
        asientos = new ArrayList<>();
        for (int i = 0; i < 25; i++) {
            asientos.add(new AsientoDTO(estadoAsiento.DISPONIBLE, "(i+1)"));
        }
        return asientos;
    }
    
    public CamionDTO camion = new CamionDTO(1L, "0000", listaAsiento);
    public CamionDTO camion2 = new CamionDTO(2L, "0001", listaAsiento);
    public CamionDTO camion3 = new CamionDTO(3L, "0002", listaAsiento);
    
    
    
  
    
    
    
    


    DefaultTableModel mt = new DefaultTableModel();

    /**
     * Creates new form ComprarViaje
     */
    public ViajesDisponibles() {
        initComponents();
        String ids[] = {"Numero", "Origen", "Destino", "Duracion", "Precio", ""};
        mt.setColumnIdentifiers(ids);
        tblViajes.setModel(mt);
 

    }

    public void cargarViajesEnTabla(List<ViajeDTO> datos) {
        DefaultTableModel modelo = (DefaultTableModel) tblViajes.getModel();
        modelo.setRowCount(0);

        // Agregar los datos a la tabla
        for (ViajeDTO viaje : datos) {
            modelo.addRow(new Object[]{
                viaje.getIdCamion(),
                viaje.getOrigen(),
                viaje.getDestino(),
                viaje.getDuracion(),
                viaje.getPrecio(),
                "Comprar"
            });
        }

        // Hacer que las columnas no sean redimensionables
        for (int i = 0; i < tblViajes.getColumnCount(); i++) {
            tblViajes.getColumnModel().getColumn(i).setResizable(false);
        }

        // Deshabilitar mover columnas
        tblViajes.getTableHeader().setReorderingAllowed(false);

        // Hacer que la tabla no sea editable
        tblViajes.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 201, 98));
        Header.setPreferredSize(new java.awt.Dimension(520, 60));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 48)); // NOI18N
        jLabel1.setText("RUTAPP");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BackGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        Footer.setBackground(new java.awt.Color(255, 201, 98));
        Footer.setPreferredSize(new java.awt.Dimension(520, 60));

        btnVolver.setBackground(new java.awt.Color(255, 201, 98));
        btnVolver.setFont(new java.awt.Font("Roboto Condensed Black", 1, 13)); // NOI18N
        btnVolver.setText("Volver\n");
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver.setPreferredSize(new java.awt.Dimension(128, 28));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 369, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackGround.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 60));

        tblViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViajes);
        if (tblViajes.getColumnModel().getColumnCount() > 0) {
            tblViajes.getColumnModel().getColumn(0).setResizable(false);
            tblViajes.getColumnModel().getColumn(1).setResizable(false);
            tblViajes.getColumnModel().getColumn(2).setResizable(false);
            tblViajes.getColumnModel().getColumn(3).setResizable(false);
        }

        BackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 460, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        BuscarViaje srcT = new BuscarViaje();
        srcT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    public ViajesDisponibles(JPanel BackGround, JPanel Footer, JPanel Header, JButton btnVolver, JLabel jLabel1, JScrollPane jScrollPane1, JTable tblViajes) throws HeadlessException {
        this.BackGround = BackGround;
        this.Footer = Footer;
        this.Header = Header;
        this.btnVolver = btnVolver;
        this.jLabel1 = jLabel1;
        this.jScrollPane1 = jScrollPane1;
        this.tblViajes = tblViajes;
    }

    private void tblViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViajesMouseClicked
        // Obtener la fila y columna donde se hizo clic
        int row = tblViajes.rowAtPoint(evt.getPoint());
        int col = tblViajes.columnAtPoint(evt.getPoint());

        // Verificar si la columna es la 6 columna (índice 5)
        if (col == 5) {
            // Obtener los datos de esa fila y columna

            Object idCamion = tblViajes.getValueAt(row, 0);
            Object origen = tblViajes.getValueAt(row, 1);
            Object destino = tblViajes.getValueAt(row, 2);
            Object duracion = tblViajes.getValueAt(row, 3);
            Object precio = tblViajes.getValueAt(row, 4);

            StringBuilder texto = new StringBuilder();
            texto.append("ID Camión: ").append(idCamion).append("\n")
                    .append("Origen: ").append(origen).append("\n")
                    .append("Destino: ").append(destino).append("\n")
                    .append("Duración: ").append(duracion).append("\n")
                    .append("Precio: ").append(precio);

// Mostrar el mensaje en un JOptionPane
            JOptionPane.showMessageDialog(this, texto.toString());
            CordinadorPresentacion.getInstancia().abrirAsientosDisponibles();
            this.dispose();
        }
    }//GEN-LAST:event_tblViajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViajesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViajesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViajesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViajesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViajesDisponibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViajes;
    // End of variables declaration//GEN-END:variables
}
